### ISSUE TITLE
Pyproj error

### ISSUE THREAD

**Issue by vsilwal** [thurinj/specfem_tomo_helper#10]
I am getting the following error when running the example:
```(mtuq) vipul@Ganga:~/REPOSITORIES/specfem_tomo_helper/examples$ python example_specfem_tomo_helper.py
/home/vipul/REPOSITORIES/specfem_tomo_helper/specfem_tomo_helper/fileimport/ncimport.py:71: RuntimeWarning: Mean of empty slice
  if 'rho' in varname and np.nanmean(var_data[:,:,0])<50:
Traceback (most recent call last):
  File "example_specfem_tomo_helper.py", line 32, in <module>
    myProj = define_utm_projection(11, 'N')
  File "/home/vipul/REPOSITORIES/specfem_tomo_helper/specfem_tomo_helper/projection/utm_projection.py", line 32, in define_utm_projection
    utm_projection = Proj("+proj=utm +zone="+str(utm_zone)+", +north +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
  File "/home/vipul/miniconda3/envs/mtuq/lib/python3.8/site-packages/pyproj/proj.py", line 109, in __init__
    self.crs = CRS.from_user_input(projparams, **kwargs)
  File "/home/vipul/miniconda3/envs/mtuq/lib/python3.8/site-packages/pyproj/crs/crs.py", line 501, in from_user_input
    return cls(value, **kwargs)
  File "/home/vipul/miniconda3/envs/mtuq/lib/python3.8/site-packages/pyproj/crs/crs.py", line 348, in __init__
    self._local.crs = _CRS(self.srs)
  File "pyproj/_crs.pyx", line 2352, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: +proj=utm +zone=11, +north +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)
```
Making the following changes fixes the issue: 
```
utm_projection = Proj(proj='utm', zone=utm_zone, hemisphere='N',ellps='WGS84',datum='WGS84', preserve_units=False)
```

This might be because of pyproj version (3.4.0) is am using.

**Comment by thurinj** [comment]
Hi @vsilwal, thanks for reporting. I've addressed this by changing the input syntax from the old string inputs that Pyproj was using back-then, with the argument-based inputs. 
I used `units='m'` rather than `preserve_units=False`. They should both be equivalent, but I find the first option more explicit. I will change it if it turns out that there is a contraindication to using this syntax.
Please let me know if that addresses your issue.
